DROP DATABASE IF EXISTS xiangling;

CREATE DATABASE xiangling DEFAULT CHARSET utf8 COLLATE utf8_general_ci;

use xiangling;

CREATE TABLE COMMON_SEQUENCE (ORDERCODE INT NOT NULL) TYPE=MYISAM;
INSERT INTO COMMON_SEQUENCE VALUES(0);